on:
  workflow_call:
    inputs:
      LOCAL_PATH:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      RELEASE_REVISION:
        required: true
        type: string

name: Build Helm Package

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - name: Prep helm chart
      run: |
        mv ${{ inputs.LOCAL_PATH }}/Chart.yaml ${{ inputs.LOCAL_PATH }}/Chart.old.yaml &&
        cat ${{ inputs.LOCAL_PATH }}/Chart.old.yaml | grep -Ev "appVersion|version" > ${{ inputs.LOCAL_PATH }}/Chart.yaml &&
        echo -e "\r\nappVersion: ${{ env.RELEASE_REVISION }}\r\n" >> ${{ inputs.LOCAL_PATH }}/Chart.yaml &&
        echo -e "\r\nversion: ${{ env.RELEASE_REVISION }}\r\n" >> ${{ inputs.LOCAL_PATH }}/Chart.yaml &&
        cat ${{ inputs.LOCAL_PATH }}/Chart.yaml  
    - name: Install s3 helm plugin
      uses: WyriHaximus/github-action-helm3@v2
      with: 
        exec: helm plugin install https://github.com/hypnoglow/helm-s3.git
    - name: Helm package chart
      uses: WyriHaximus/github-action-helm3@v2
      with: 
        exec: helm package ${{ inputs.LOCAL_PATH }}
        kubeconfig: '${{ secrets.KUBE_CONFIG_GROKIT_DEV }}'
    - name: Helm add repo
      uses: WyriHaximus/github-action-helm3@v2
      with: 
        exec: helm repo add ${{ env.DEPLOYMENT }} ${{ env.HELM_CHART_REPO }}/${{ env.DEPLOYMENT }}
        kubeconfig: '${{ secrets.KUBE_CONFIG_GROKIT_DEV }}'
    - name: Helm push chart
      uses: WyriHaximus/github-action-helm3@v2
      with: 
        exec: helm s3 push --relative --force ./${{ env.DEPLOYMENT }}-${{ env.RELEASE_REVISION }}.tgz ${{ env.DEPLOYMENT }}
        kubeconfig: '${{ secrets.KUBE_CONFIG_GROKIT_DEV }}'