on:
  workflow_call:
    inputs:
      ECR_REGISTRY:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      RELEASE_REVISION:
        required: true
        type: string

name: Build and push docker image

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - name: Build & Push Image
      env:
        ECR_REGISTRY: ${{ inputs.ECR_REGISTRY }}
        RELEASE_IMAGE: ${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.RELEASE_REVISION }}
      run: |
        DOCKER_OPTS="${DOCKER_OPTS} --registry-mirror=https://mirror.gcr.io"  docker build -t ${{ inputs.ECR_REPOSITORY }}:${{ inputs.RELEASE_REVISION }} . -f ontology-graphql/docker/Dockerfile --build-arg GITHUB_TOKEN
        docker tag ${{ inputs.ECR_REPOSITORY }}:${{ inputs.RELEASE_REVISION }} ${{ env.RELEASE_IMAGE  }}
        docker push ${{ env.RELEASE_IMAGE  }}