on:
  workflow_dispatch:
    inputs: 
      Action: 
        type: boolean
        description: "Run workflow"
        required: true

permissions: read-all

name:  '# Current version is v1.1.1 #'
run-name: Building changelog

jobs:
  changelog:
    if: ${{ github.event.inputs.Action }}

    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Get Version
      run: |
        echo "Changelog

        v1.1.1
        - Add paralogue version selection for clete apps

        v1.1.0
        - Use helm chart for deploys to dev and test
        - Add app version number to run deploy title

        v1.0.0
        - Configure reuse workflows
        "
